### ISSUE TITLE
Improvements to the Land model in AMIP; DRAFT

### ISSUE THREAD

**Issue by LenkaNovak** [CliMA/ClimaLand.jl#127]
The intent of this SDI is to summarize in on place all the efforts to improve the land model used in AMIP. Each individual effort has its own SDI.

Following discussions over the last week or so, it would be beneficial to clarify the steps of the canopy implementation using an SDI, so that different teams can prioritize their work efforts, keep track and progress together efficiently. In addition, there were questions about:
- are we implementing the Big Leaf(s) model as the first step? *Yes.*
- are we ok to use MOST all the way to the surface (even inside canopy), which is then modified by a resistance for evaporation after, and which uses a canopy height for parameterizing roughness length, for the first prototype (as in the SLIM model, see supplemental material [here](https://journals.ametsoc.org/view/journals/clim/32/18/jcli-d-18-0812.1.xml))? Some of us thought we want to stay away from MOST inside the canopy (see SurfaceFluxes.jl effort below.)
- is there an existing test case that we want to couple to ClimaLSM and then to the Coupler? What are the inputs/outputs?
- (how /when) will the plant hydraulics model of @kmdeck and @gagnelandmanna be incorporated? *We will use it for the plant hydraulics model*

## Current work efforts
- `SurfaceFluxes.jl`  [@akshaysridhar , @LenkaNovak , @tapios ]
  - [working branch](https://github.com/CliMA/SurfaceFluxes.jl/blob/as/PG95-rsl/src/SurfaceFluxes.jl#L958), docs: Overleaf DesignDoc, section 5.3.1
      - purpose: it will add a roughness sublayer, which uses a modified version of MOST, valid between displacement height (e.g. 0.8*canopy height) and z_star (which is typically a function of the planetary boundary layer height `z_star = 0.04h_PBL`)
      - notes:
        - between displacement height and surface, we recommend second order interpolation for cases where prescribed profiles of tracers and u through the canopy are needed. An alternative is Harman and Finnigan 08 / Bonan 18 implementation, which we can add when needed (though this may require a modification to the theory)
      - status: function implemented, currently adding tests 
  - another extension may be to consider the surface viscous sublayer (that accounts for transfer across a thin quasi-laminar boundary layer of air in contact with a surface) as in [here](https://www.sciencedirect.com/science/article/abs/pii/S0022169415002681), but this would require more discussion/design later on
- `ClimaLSM` 
  - https://github.com/CliMA/ClimaLSM.jl/pull/125
    - purpose: adds in the capability to read in a NetCDF file of soil albedo from a file  
    - status: merged
  - https://github.com/CliMA/ClimaLSM.jl/pull/124
    - purpose: Updates how we handle evaporation when the bucket is not saturated: E = beta*E_0(q_sat) 
    - status: merged
  - https://github.com/CliMA/ClimaLSM.jl/issues/152 [@braghiere , @AlexisRenchon, @kmdeck  ] 
    - purpose: adds big leaf model, running with plant hydraulics and the soil model
    - status: merged
  - https://github.com/CliMA/ClimaLSM.jl/issues/146 [@kmdeck, @a-charbon, @shuangma1990]
    - Adds standalone snow model, next step would be to run with the soil/canopy model
    - status: on hold, but we have integrated model (below)
  - https://github.com/CliMA/ClimaLand.jl/issues/630
    - Integrates snow model with soil/canopy model --> `LandModel`
    - status: merged
  - https://github.com/CliMA/ClimaLSM.jl/issues/161 [@kmdeck]
    - Adds ability to run soil model with prescribed atmos and radiation (soil evaporation, albedo, emissivity)
    - status: merged
  - https://github.com/CliMA/ClimaLSM.jl/issues/135 [@juliasloan25, @dennisYatunin]
    - Implicit solver for soil
    - status: merged

**Comment by LenkaNovak** [comment]
@braghiere would you be interested in leading the SDI, since you're in charge of Land's 🍐 sessions on this? 🙏

**Comment by kmdeck** [comment]
We have completed the items in this SDI, so I am closing it. We will open another issue to describe any changes that need to be made to the Clima Land model when coupling it to atmos. @juliasloan25
