### ISSUE TITLE
Add test for `FileReader.interpolate_data`

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLand.jl#285]
**Is your feature request related to a problem? Please describe.**
We currently have a test for `interpolate_data` in the FileReader module, but it doesn't test all functionality of the function. Specifically, it doesn't test behavior when we try to interpolate data at a date that appears in the input file.
Please link to any related issues/PRs.

**Describe the solution you'd like**
There is a test similar to what we need to implement here in `test/standalone/Bucket/albedo_types.jl`. We should replicate that test with only the components needed for `interpolate_data` testing, and add it to `test/shared_utilities.file_reader.jl`.

**Comment by Sbozzolo** [comment]
Closing this, as the `FileReader` module is no longer in `ClimaLand`.
