### ISSUE TITLE
Pass the comms in; do not relay on internal ClimaCore comms values

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#316]
**Is your feature request related to a problem? Please describe.**
We currently rely on default comms values set in ClimaCore. These will be deprecated and we should instead pass in the comms context/device ourselves.

#315 

**Describe the solution you'd like**
Pass comms via the domain constructors. we can have a default value of the Singleton if we want.

**Questions**
Do we need to pass in the comms/device anywhere else?

**Comment by juliasloan25** [comment]
we now pass the comms context for each space we construct
