### ISSUE TITLE
Add parameters to CLIMAParameters

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#326]
We need to go through our models and add any physical constants, calibrated parameters, or global parameters to CLIMAParameters. Then we need to update our land parameter set to include them, and get them from there.

- [X] ID parameters that need to be moved (@nefrathenrici, @braghiere, @AlexisRenchon, @kmdeck)
- [x] Open PR in CLIMAParameters that adds them with default or set values @nefrathenrici  
- [ ] PR in ClimaLSM that adds them to the land parameter set and removes them from the other param sets where they are stored; uses them from land parameter set. @nefrathenrici  
- [ ] Document the steps somewhere (in a tutorial?) so that it is easy for someone else to replicate this when they add in future parameters (maybe already in ClimaParameters)

Note that parameters that are read from files (spatially varying, driver data, etc) will not be in CLIMAParameters.

**Comment by AlexisRenchon** [comment]
Would it be a good occasion to move `parameters/create_parameters.jl` into `src/shared_utilities/create_parameters.jl` and add `CLIMAParameters.jl` as a dependency to `ClimaLSM.jl`? (we discussed that a bit a while ago)

Should we have a meeting (not sure with who) to discuss exactly how (standardized across atmosphere, ocean, land) to add calibrated parameters, physical constants, and global parameters in CLIMAParameters.jl? There should be docs for this in both repo.

**Comment by kmdeck** [comment]
> Should we have a meeting (not sure with who) to discuss exactly how (standardized across atmosphere, ocean, land) to add calibrated parameters, physical constants, and global parameters in CLIMAParameters.jl? There should be docs for this in both repo.

We should talk with Nat or Ollie, I think. Nat has been handling a lot of the parameter interfacing for the atmosphere model, and Ollie is the lead on the clima parameters side. @nefrathenrici would you have time for a meeting next week?

Regarding the dependency on CLIMAParameters - Im not sure! What was the resolution from the previous discussion? We can follow what Atmos/Thermodynamics/SurfaceFluxes does?

**Comment by AlexisRenchon** [comment]
Charles had said:

"Regarding the parameters, we ended up caving and moving the convenience functions for creating parameters into src. @glwagner was petitioning to make packages independent of CLIMAParameters, but this ends up increasing the boilerplate of driver scripts. One thing I will say, though, is that users should not have to use ClimaParameters to make parameters for the package. That is, for example, there should not be an inner constructor for https://github.com/CliMA/Thermodynamics.jl/blob/b62d6d27b512fd594ccd2d982b378b9848464016/src/Parameters.jl#L21 that requires ClimaParameters. Having an inner constructor for that function would require users to depend on CLIMAParameters to use the package, which is inconvenient."

in the docs overhaul issue (#240)

**Comment by kmdeck** [comment]
Parameters in the soil model that are globally constant and can be added to ClimaParameters now:
- a, b of Kersten number model
- Omega (ice impedance effect on hydraulic K)
- gamma, gamma_ref (viscosity dependence of hydraulic K on T_soil)
- K_quartz, minerals, organic matter, ice, and liquid - required to computed thermal K of soil
- z_0m for bare soil

**Comment by kmdeck** [comment]
@braghiere @AlexisRenchon could you ID the parameters in the canopy model which are globally constant? we can move those to ClimaParameters in one PR with the soil parameters. This is on my list to do by the sprint, if that timing works for you in terms of preparing the list.

thanks!

**Comment by AlexisRenchon** [comment]
Another thought: should we try having unique parameter name? Currently, we have many parameters that have the same name (for example, gamma or f or k). It works fine in the model because these are just functions arguments. But for clarity and when we centralize all parameters, would we want unique name? I don't mind either way, but we can think about it.

**Comment by kmdeck** [comment]
> Another thought: should we try having unique parameter name? Currently, we have many parameters that have the same name (for example, gamma or f or k). It works fine in the model because these are just functions arguments. But for clarity and when we centralize all parameters, would we want unique name? I don't mind either way, but we can think about it.

in ClimaParameters we will need a unique name, internally we can call it what we want though. so we can decide if we want to change the names or if it will be clear based on context? Maybe best to stick to the convention used in each field? Agreed, let's think about it :)
