### ISSUE TITLE
convert dates to `DateTime`, remove `to_datetime` calls

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLand.jl#333]
When reading in a data file over time, `to_datetime` is called at each timestep to convert the current time of the simulation to a `DateTime`, then to compare this to the date stored in the data file. Both of these calls can be removed if we convert all dates of input data files to `DateTime`s before running the simulation, and store new data files using this type. We can just do this once for each input file we expect to use. Then, in preprocessing, we can assert that all input data files use `DateTime`s to store date information.

See in ClimaLSM: [call 1](https://github.com/CliMA/ClimaLSM.jl/blob/main/src/standalone/Bucket/Bucket.jl#L635C28-L635C28) and [call 2](https://github.com/CliMA/ClimaLSM.jl/blob/main/src/standalone/Bucket/Bucket.jl#L640).

We still want to keep this function in TimeManager so we can use it for this preprocessing step.
Please link to any related issues/PRs.

### To Do
- [ ] convert dates of all input data files to `DateTime` type, and save as new data files. Use these pre-processed files going forward
- [ ] make sure `date_ref` is always a `DateTime` type
- [ ] remove extra `to_datetime` calls
- [ ] use function from ClimaUtilities.jl TimeManager [not yet implemented - https://github.com/CliMA/ClimaUtilities.jl/issues/12] to assert that data files use `DateTime` dates before running simulations

**Comment by Sbozzolo** [comment]
Closing because input data managment is now in ClimaUtilities.
