### ISSUE TITLE
test TempestRemap on windows

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLand.jl#422]
**Is your feature request related to a problem? Please describe.**
TR should work using the latest package versions (CCTR, HDF5, etc). We should test this out by running all our tests on windows (remove if !windows checks)

## Update
ClimaCoreTempestRemap casts a `long *` to a `size_t *` in [this line](https://github.com/ClimateGlobalChange/tempestremap/blob/master/src/netcdf.cpp#L1125C85-L1125C90), which point to different sizes of memory on windows. So we won't be able to use TempestRemap on Windows after all.

**Comment by kmdeck** [comment]
aw, too bad. well, we can offer non-global runs to people with windows, in any case!

perhaps relevant for @simonbyrne to know but not a priority

**Comment by juliasloan25** [comment]
issue opened here: https://github.com/ClimateGlobalChange/tempestremap/issues/121
