### ISSUE TITLE
Disordered kinetics module for SOC decomposition

### ISSUE THREAD

**Issue by AlexisRenchon** [CliMA/ClimaLand.jl#470]
**Is your feature request related to a problem? Please describe.**
In a transient climate, ESMs need to predict the fraction of CO2 emitted by human activity that will remain in the atmosphere. To date, about 50% of CO2 emissions stays in the atmosphere, the rest is absorbed by ocean and land sink (about 25% each). On land, the pools of carbon can be divided into live and dead organic mass (e.g., vegetation and soil organic matter). ESMs, via LSMs, need to predict the future of these pools in that transient climate (e.g., how increased T and shifts in moisture and precip will modify those pools). 

**Describe the solution you'd like**
There is no clear consensus in the best approach to model the fate of soil organic carbon (it is also very difficult to validate as there are no global data of change in SOC). Most LSMs use a model called "CENTURY", which partition SOC into a finite number of pools, e.g., 3 pools, "active", "slow", "passive", where each pool decay at a rate k, k being big or small depending on which pool. 
Another approach, that we implemented in CliMA, is to a more mechanistic approach with only one pool, were soil C gets decomposed at a rate function of temperature, moisture, and oxygen content in the porous air space. (these variables varying with depth in the discretized soil domain). 

**Describe alternatives you've considered**
The new approach of this SDI would be to implement a "disordered kinetics" approach, where an infinite number of soil C pools gets decomposed at different decay rate k, where k follows a probability density function. In this approach, k is determined by the age of organic matter and, in space, environmental variables such as mean temperature or moisture. 

**Additional context**
Advantages of disordered kinetics:
- elegant mathematically
- easy to parameterize
- can make use of global datasets of live C turnover and soil C age
- is built to track pool change at larger time scale rather than fluxes on short time scale

Disadvantages of disordered kinetics: 
- works well in a steady state world, might not be ideal for a transient climate
- does not partition decomposition of soil C into CO2 and CH4, which is a problem as these 2 molecule have a very different radiative forcing that matters for climate
- require space for time substitution that may or may not be appropriate
- may not work well on short time scale, making it impossible to benchmark at hourly, diurnal and seasonal time scale

**Comment by flamholz** [comment]
About the disadvantages you wrote down.
* Seems like the existing models don't work in a general sense, so maybe steady-state is a good start? 
* Can be done with 1 additional parameter for a partition coefficient, or two for separate k dists. 
* Space for time is done to address data limitations that apply globally, I think this is an issue that is more general (i.e. limited data on time/age/age dists) 
* Tapio argued that it's worth figuring out if it works on short timescales. Seems to me likely that it *can* work on short timescales but perhaps not with the same parameterizations that work on long timescales.

**Comment by AlexisRenchon** [comment]
@flamholz @cfranken 
```
Seems like the existing models don't work in a general sense, so maybe steady-state is a good start?
```
That would be a great point of discussion to introduce the problem in a paper. 
I think we would need to be specific about what is the model goal. Two well known examples are: 
- modeling current SOC pools (this is assuming steady climate for a spin-up until SOC reaches equilibrium i.e., inputs = outputs). Current models do indeed a bad job to spin-up SOC, particularly in the permafrost regions. This may be due to different things: bad models, or maybe also we can't assume SOC is the result of steady state of current condition (but rather, a legacy or past conditions). 
- modeling future SOC (e.g., in 2100). This can start (SOC initial condition) from spin-up equilibrium SOC (which would be wrong) or from observed SOC. Regardless, it is impossible to say what the "true" future SOC is. BUT, what we can say, is that there is very large uncertainties between models. Again, this can be discussed further. The uncertainties from ESMs can be the result of different SOC models, or different future environmental condition predicted by different ESMs. 
A good review of the literature on this would be a great intro to what disordered kinetics could add. 

```
Can be done with 1 additional parameter for a partition coefficient, or two for separate k dists.
```
Is this about partitioning decay into CO2 and CH4? That's a good idea and we should test it! This is definitely necessary for climate models, where it is the goal to predict future GHG concentration in the atmosphere. (another model goal could simply focus on change in SOC, but climate model do need CO2 and CH4). Let's keep this in mind! 

```
Space for time is done to address data limitations that apply globally, I think this is an issue that is more general (i.e. limited data on time/age/age dists)
```
I agree, but my point still stands, right? Sometimes space for time is a valid assumption, sometime not. We need to test it. And also, space for time cannot be done if there is no space that represent future time condition. 

```
Tapio argued that it's worth figuring out if it works on short timescales. Seems to me likely that it can work on short timescales but perhaps not with the same parameterizations that work on long timescales.
```
Yes, let's test it on short timescale. It is a bit a weird situation, climate model do not really care about short timescale, but we need it to benchmark models and convince peers that it works.
