### ISSUE TITLE
The Vaira data link stopped working

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#601]
## Describe the bug
Our Vaira test site in experiments stopped working because the data_link is no longer valid. 
We just need to fix the link and add back to buildkite pipeline.yml, but it's not clear exactly what file in box that link pointed to.

**Comment by Sbozzolo** [comment]
It might be a good time to move to using artifacts.

In the meantime, I think we can disable the test, as in bb2a3312238ed39caad4c045180f034c9e206ced
