### ISSUE TITLE
Nonlinearsolver package and compat

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#62]
**Is your feature request related to a problem? Please describe.**
Nonlinear solvers works on GPUs - we may want to use that instead of NLSolve
Add compat helpers.

Please link to any related issues/PRs.

**Describe the solution you'd like**
Switch from NLSolve to Nonlinear solvers if applicable
Use CompatDevTools or add compat entries for test Project.toml.

(These are improvements that were suggested during a pair program session with Charlie)

**Comment by Sbozzolo** [comment]
I think this issue is stale, can we close it?

**Comment by kmdeck** [comment]
fine with me!
