### ISSUE TITLE
Fix documentation: stable is outdated

### ISSUE THREAD

**Issue by AlexisRenchon** [CliMA/ClimaLand.jl#681]
Our stable docs is very outdated, https://clima.github.io/ClimaLand.jl/stable/ is stuck at v0.2.2.

We currently link (in our README) to the [dev docs](https://clima.github.io/ClimaLand.jl/dev/), but ideally, we want stable docs to be up-to-date. 

Note: the version tracking of our docs is also broken, this may due to the same issue.

**Comment by Sbozzolo** [comment]
This was fixed by adding the DOCUMENTER_KEY
