### ISSUE TITLE
Include start date when saving diagnostics as NCDataset

### ISSUE THREAD

**Issue by ph-kev** [CliMA/ClimaLand.jl#879]
When the diagnostics are saved as NCDatasets after a simulation, the start date is not available in the attributes.

The start dates should be saved in the attributes in the NCDataset so that one doesn't need to go to the simulation that generate the data and find the start date of the simulation.

**Comment by AlexisRenchon** [comment]
Done in #893 and ClimaDiagnostics https://github.com/CliMA/ClimaDiagnostics.jl/pull/94 + https://github.com/CliMA/ClimaDiagnostics.jl/pull/96
