### ISSUE TITLE
Consolidate spatially varying parameters  in sim setup

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaLand.jl#882]
**Is your feature request related to a problem? Please describe.**
We define spatially varying parameters in multiple experiment scripts in the same way, e.g.
experiments/long_runs/soil.jl
experiments/long_runs/land*.jl
experiments/benchmarks/...

Meanwhile, in experments/integrated/global/, we set up a global run without the spatially varying parameters. This is the only test that runs in CI each time (benchmarks and long runs are optional). Because of this, our "long run" setup is not tested regularily.

**Describe the solution you'd like**
Make a "spatially_varying_soil_parameters()" function and a "spatially_varying_canopy_parameters()" function which return our default setup. This can live in src, maybe in a src/simulations/ folder?

Ultimately this will be superceded/used in the Simulations objects, but this is a temporary fix to reduce code duplication and improve testing.

@AlexisRenchon @Sbozzolo I would like to do this as a quick fix, but let me know if you seen any issues with what I outline above.

**Comment by Sbozzolo** [comment]
Yes, I am on board. Maybe, give a more descriptive name (e.g., clm_canopy_parameters).
