### ISSUE TITLE
Remove Plots.jl dependency

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaLand.jl#927]
**Is your feature request related to a problem? Please describe.**
Our codebase currently uses both Makie.jl and Plots.jl. It would be good to converge to using only Makie.jl and remove the extra Plots.jl dependency, to decrease our overall number of dependencies and decrease precompilation time.

This will also decrease precompilation time downstream in ClimaCoupler.jl once we remove the Plots.jl dependency there.

**Comment by imreddyTeja** [comment]
Plots.jl is not a dependency of the ClimaLand package. All of the instances of Plots.jl usage are in the docs or experiments, so I don't think this will decrease pre-compilation time in ClimaCoupler.

**Comment by juliasloan25** [comment]
> Plots.jl is not a dependency of the ClimaLand package. All of the instances of Plots.jl usage are in the docs or experiments, so I don't think this will decrease pre-compilation time in ClimaCoupler.

In this issue I meant to remove it from where it's used in docs and experiments, which was done in https://github.com/CliMA/ClimaCoupler.jl/pull/1097. This is also a duplicate of https://github.com/CliMA/ClimaCoupler.jl/issues/1091 😅
